# Generated by Django 4.2.4 on 2023-09-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_username_usercreate_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='sale_count',
            field=models.IntegerField(default=0),
        ),
    ]
