# Generated by Django 4.2.4 on 2023-09-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usercreate_vip_subscription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='vip_subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='vip_subscription_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
