# Generated by Django 4.2.4 on 2023-09-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_usercreate_vip_subscription_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='vip_subscription_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='usercreate',
            name='vip_subscription_expiration_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
