# Generated by Django 4.2.4 on 2023-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usercreate_vip_subscription_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
