# Generated by Django 4.2.4 on 2023-09-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0003_remove_file_attached_files_attachedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='attached_files',
            field=models.ManyToManyField(blank=True, related_name='attached_to', to='filesApp.file'),
        ),
        migrations.DeleteModel(
            name='AttachedFile',
        ),
    ]
