# Generated by Django 4.2.4 on 2023-09-14 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0004_file_attached_files_delete_attachedfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='attached_files',
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', models.FileField(upload_to='attached_files/')),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='filesApp.file')),
            ],
        ),
    ]
