# Generated by Django 4.2.4 on 2023-09-14 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0006_remove_attachedfile_parent_file_file_parent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='parent_file',
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='parent_file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attached_files', to='filesApp.file'),
        ),
    ]
