# Generated by Django 4.2.4 on 2023-09-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0009_alter_purchase_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='filesApp.file'),
        ),
    ]
