# Generated by Django 4.2.4 on 2023-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0010_alter_purchase_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='file',
        ),
        migrations.AddField(
            model_name='purchase',
            name='buyer_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='file_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
