# Generated by Django 4.2.4 on 2023-09-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0011_remove_purchase_buyer_remove_purchase_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='buyer_phone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
