# Generated by Django 4.2.4 on 2023-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesApp', '0012_purchase_buyer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='buyer_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='file_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
